### PR TITLE
Add HTTPS support.

### PR DESCRIPTION
**Pull request by codyhanson**
Add new -s or --secure option to force the use of https.

### CODE REVIEW

**Comment by FGRibreau** [comment]
Thanks a lot @codyhanson for your various PR!

**Comment by codyhanson** [comment]
Thanks to you too! I was just about to write my own CLI for influx when I found this one this morning.

**Comment by FGRibreau** [comment]
Nice! I could definitely add you as a collaborator on influxdb-cli if you want :)

**Comment by codyhanson** [comment]
Perhaps, My company recently started using InfluxDB for some of our
applications, so it is possible that I will have more contributions.

Cody Hanson

**Comment by FGRibreau** [comment]
Ok, we'll see then :)

**Pull request merged**
